FROM texlive/texlive:TL2025-historic-with-cache
RUN apt update
RUN apt install -qy fonts-lohit-deva
RUN luaotfload-tool -u || true
RUN cp "$(find /usr/local/texlive -name texlive-fontconfig.conf)" /etc/fonts/conf.d/09-texlive-fonts.conf || true
RUN fc-cache -fsv
